export const stages = [
  {name:'Discover', headline:'Start with a what if.', text:'Follow a question. Explore an interest. Find a problem you actually want to solve.', action:'Your move: ask a better question.'},
  {name:'Develop', headline:'Give your idea some tools.', text:'Learn a concept, try it out, get stuck, and try again. Practice is where understanding takes shape.', action:'Your move: make a first attempt.'},
  {name:'Demonstrate', headline:'Make something you can show.', text:'Turn the learning into a project. Explain your choices, test your work, and make your thinking visible.', action:'Your move: put it to the test.'},
  {name:'Evolve', headline:'Build. Reflect. Go again.', text:'Use feedback to make the next version better. Collect the work and the lessons you want to carry forward.', action:'Your move: improve one thing.'}
];
export const programs = [
 {slug:'build-for-the-web',category:'Code',name:'Build for the web',line:'From a blank browser to something that works.',symbol:'</>',color:'blue',level:'Beginner concept',skills:['HTML & CSS','JavaScript','Accessibility'],project:'A website for a cause you care about',description:'Explore how the web works by designing and building a small, useful website. Start with a real need, then turn structure, style, and interaction into a working experience.',outcomes:['Structure a page with meaningful HTML.','Create layouts that adapt to different screens.','Add an interaction with JavaScript and explain how it works.','Test your website with a keyboard and a real person.'],modules:[['Understand the web','Map a visitor’s goal, sketch a page, and learn how browsers turn files into an experience.'],['Build the foundation','Work with headings, links, forms, and semantic HTML. Give every element a job.'],['Make it feel right','Explore responsive CSS, typography, spacing, and accessible contrast.'],['Make it work','Add one useful JavaScript interaction, test edge cases, and document your decisions.']],brief:'Choose a cause on your campus or in your community. Build a three-page website that helps someone understand it and take one clear action.',deliverables:['A responsive website','A short design and build log','An accessibility and usability check'],need:'Suggested starting point: curiosity about websites and access to a laptop. Final eligibility and tools will be confirmed before enrolment.'},
 {slug:'make-sense-of-data',category:'Data',name:'Make sense of data',line:'Turn “I think” into “here’s what I found.”',symbol:'↗',color:'yellow',level:'Beginner concept',skills:['Spreadsheets','Data cleaning','Visual storytelling'],project:'An evidence-backed answer to an everyday question',description:'Learn to ask useful questions, work with a small dataset, and tell an honest story with evidence. The goal is understanding what the numbers can—and cannot—say.',outcomes:['Turn a broad question into something measurable.','Organize and clean a small dataset.','Choose a chart that makes a comparison clear.','Explain a finding, its limitations, and a sensible next step.'],modules:[['Ask a measurable question','Choose a decision that data could help with. Define what you need to measure.'],['Get the data ready','Spot missing values, duplicates, and inconsistent labels in a sample dataset.'],['Explore and visualize','Use basic summaries and charts to look for patterns without overstating them.'],['Tell the whole story','Write a short evidence-based recommendation, including uncertainty and limitations.']],brief:'Use a fictional campus café dataset to investigate when queues are longest. Recommend one practical change and explain what extra evidence you would need.',deliverables:['A cleaned sample dataset','A visual findings sheet','A recommendation with limitations'],need:'Suggested starting point: comfort with basic arithmetic and access to a spreadsheet tool. Final eligibility will be confirmed before enrolment.'},
 {slug:'design-for-real-people',category:'Design',name:'Design for real people',line:'Notice a little friction. Make a better experience.',symbol:'↳',color:'pink',level:'Beginner concept',skills:['Problem framing','Prototyping','User testing'],project:'A simpler experience for an everyday task',description:'Explore design as a way to solve problems. Observe an everyday task, sketch a better approach, and use feedback to improve a small prototype.',outcomes:['Describe a problem from the user’s point of view.','Sketch more than one possible solution.','Create a low-fidelity interactive or paper prototype.','Run a small usability check and act on what you learn.'],modules:[['Notice the friction','Observe a task and separate what people do from what you assume they need.'],['Explore possibilities','Write a clear problem statement and sketch multiple solutions.'],['Build a small prototype','Choose one idea and make just enough of it for someone to try.'],['Listen and iterate','Observe a test, record the evidence, and make a thoughtful improvement.']],brief:'Redesign the way someone finds a free study space. Create a simple flow that answers where, when, and how to book, then test it with a willing participant.',deliverables:['A problem statement','A prototype and test notes','A before-and-after design rationale'],need:'Suggested starting point: an interest in people and how things work. Paper and a pen are enough to begin. Final eligibility and tools will be confirmed.'},
 {slug:'explore-ai',category:'AI',name:'Explore AI, thoughtfully',line:'Experiment with the tools. Keep your judgment.',symbol:'✳',color:'mint',level:'Beginner concept',skills:['AI literacy','Prompt experiments','Evaluation'],project:'A tested AI-assisted study workflow',description:'Explore what AI tools can help with, where they fall short, and how to evaluate their output. Build a small workflow while keeping accuracy, privacy, and your own thinking in the loop.',outcomes:['Describe a useful task and set a clear success criterion.','Compare different prompts against the same task.','Check an AI output against a trusted source.','Document risks, limitations, and where human review is needed.'],modules:[['Know the tool','Explore capabilities, common failure modes, and the difference between a fluent answer and a reliable one.'],['Design an experiment','Write a task, choose a test input, and compare two prompt approaches.'],['Evaluate the result','Check accuracy, relevance, and uncertainty. Avoid using private or sensitive information.'],['Build a responsible workflow','Combine a tool with human checks and explain when the workflow should not be used.']],brief:'Design a workflow that turns your own non-sensitive study notes into revision questions. Test the questions for accuracy and usefulness, and document the human checks.',deliverables:['A documented prompt experiment','An evaluation checklist','A workflow with explicit limitations'],need:'Suggested starting point: interest in AI and a willingness to question outputs. Tool access, age requirements, and eligibility will be confirmed before enrolment.'}
];
export const faqs = [
 ['Can I enrol in a program now?','Not yet. The learning paths on this website are sample concepts. Enrolment dates, confirmed curriculum, fees, and delivery details will be announced once they are ready.'],
 ['Who is ZelSpark for?','ZelSpark is being created for students who want to put their learning into practice. Age requirements, prerequisites, and school or college eligibility will be specified for each confirmed program.'],
 ['Will learning be online or in person?','Delivery mode, schedule, duration, and access requirements are still being developed. These will be published for each program before anyone enrols.'],
 ['Will there be mentors, certificates, or internships?','Mentorship and real-world exposure are part of the vision. No mentors, certificates, internships, placements, or employment outcomes are confirmed or promised on this preview website. Any future offering will have its own clear terms.'],
 ['What can parents expect?','Clear program information before enrolment: learning goals, expected effort, eligibility, support, and how work is reviewed. A parent progress dashboard is not currently available.'],
 ['Can my institution or organization collaborate?','Yes, you can explore a conversation about project briefs, learning initiatives, or mentoring. The partner page describes possible collaboration formats, not existing partnerships.']
];
export const challenges = [
 {id:'design',category:'Design',title:'Fix one tiny frustration.',intro:'Think of a task on your campus or in your daily life that takes more effort than it should. Design a simpler way to do it.',steps:['Describe the task and who needs to do it.','Sketch two ways to make it easier.','Ask a willing person to try a paper prototype.','Write down one change their feedback inspired.'],output:'One sketch. One test. One thoughtful improvement.'},
 {id:'code',category:'Code',title:'Make one useful page.',intro:'Choose something you wish had a clearer home on the web: a club, a community event, or a cause. Give it a simple page.',steps:['Write down who the page is for and its one main goal.','Build a heading, a short explanation, and a useful link.','Make it readable on a phone and usable with a keyboard.','Ask someone what they would do next and improve the page.'],output:'One working page that helps someone take the next step.'},
 {id:'data',category:'Data',title:'Question your everyday.',intro:'Pick a harmless everyday question you can investigate with a few observations, such as how your own study time is spent. Use only your own non-sensitive data.',steps:['Turn your question into something you can count.','Record a small set of observations consistently.','Create a simple chart and describe what you see.','Write one limitation and one question to investigate next.'],output:'One small chart. One honest insight. One next question.'}
];
