import {stages,programs,challenges} from './data.js';
import {contactConfig} from './config.js';
document.documentElement.classList.remove('no-js');
const $=(q,root=document)=>root.querySelector(q);
const $$=(q,root=document)=>[...root.querySelectorAll(q)];
const menu=$('.menu-toggle'),nav=$('#navigation');
function closeMenu(){nav?.classList.remove('is-open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Open navigation');}
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu();});
nav?.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
const mq=matchMedia('(min-width:851px)');mq.addEventListener('change',e=>{if(e.matches)closeMenu();});

// Native buttons remain in normal keyboard order. Arrow keys also move within groups.
function arrowNavigation(selector){const buttons=$$(selector);buttons.forEach((button,index)=>button.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[i].focus();buttons[i].click();}));}
arrowNavigation('[data-stage]');arrowNavigation('[data-filter]');arrowNavigation('[data-challenge]');

let setSceneStage=()=>{},activeStage=0;
$$('[data-stage]').forEach(button=>button.addEventListener('click',()=>{activeStage=Number(button.dataset.stage);const stage=stages[activeStage];$$('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#spark-headline').textContent=stage.headline;$('.lab-small').textContent=`0${activeStage+1} / ${stage.name.toUpperCase()}`;$('#spark-copy').textContent=stage.action;setSceneStage(activeStage);}));
if($('#spark-scene')){const loadScene=()=>import('./spark.js').then(({initSpark})=>{setSceneStage=initSpark($('#spark-scene'),$('.motion-button'));setSceneStage(activeStage);}).catch(()=>{$('.motion-button').hidden=true;});if('requestIdleCallback' in window)requestIdleCallback(loadScene,{timeout:900});else setTimeout(loadScene,80);}

let currentFilter='All';
function filterPrograms(){const query=$('#program-search').value.trim().toLowerCase();let count=0;$$('.catalog-grid .program-card').forEach(card=>{const visible=(currentFilter==='All'||card.dataset.category===currentFilter)&&card.dataset.search.includes(query);card.hidden=!visible;if(visible)count++;});$('#result-count').textContent=`${count} learning ${count===1?'path':'paths'} to explore`;$('.empty-state').hidden=count>0;}
$$('[data-filter]').forEach(button=>button.addEventListener('click',()=>{currentFilter=button.dataset.filter;$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));filterPrograms();}));
$('#program-search')?.addEventListener('input',filterPrograms);
$('#clear-filters')?.addEventListener('click',()=>{currentFilter='All';$('#program-search').value='';$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='All')));filterPrograms();$('#program-search').focus();});

function downloadText(filename,text){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let selectedChallenge=challenges[0];
const checks=new Map(challenges.map(c=>[c.id,new Set()]));
function updateProgress(){const count=checks.get(selectedChallenge.id).size;$('.challenge-progress progress').value=count;$('#challenge-progress').textContent=count===4?'4 of 4 — a first version!':`${count} of 4 steps tried`;}
function bindChecks(){$$('[data-task]').forEach(input=>input.addEventListener('change',()=>{const set=checks.get(selectedChallenge.id);input.checked?set.add(Number(input.dataset.task)):set.delete(Number(input.dataset.task));updateProgress();}));}
if($('#challenge-detail')){bindChecks();$$('[data-challenge]').forEach(button=>button.addEventListener('click',()=>{selectedChallenge=challenges.find(c=>c.id===button.dataset.challenge);$$('[data-challenge]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#challenge-title').textContent=selectedChallenge.title;$('#challenge-intro').textContent=selectedChallenge.intro;$('#challenge-output').textContent=selectedChallenge.output;$('.challenge-count').textContent=`0${challenges.indexOf(selectedChallenge)+1} / 03`;const fields=$('.challenge-checks');$$('label',fields).forEach(l=>l.remove());selectedChallenge.steps.forEach((step,i)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.dataset.task=i;input.checked=checks.get(selectedChallenge.id).has(i);const span=document.createElement('span');span.textContent=step;label.append(input,span);fields.append(label);});bindChecks();updateProgress();$('#challenge-status').textContent=`${selectedChallenge.category} challenge selected: ${selectedChallenge.title}`;}));$('#reset-challenge').addEventListener('click',()=>{checks.get(selectedChallenge.id).clear();$$('[data-task]').forEach(i=>i.checked=false);updateProgress();$('#challenge-status').textContent='Checklist reset. Ready for another attempt.';});$('#download-brief').addEventListener('click',()=>{downloadText(`ZelSpark-${selectedChallenge.id}-mini-challenge.txt`,`ZELSPARK — THE STUDIO\nSelf-guided mini challenge\n\n${selectedChallenge.title}\n\n${selectedChallenge.intro}\n\nYOUR FOUR SMALL MOVES\n${selectedChallenge.steps.map((s,i)=>`${checks.get(selectedChallenge.id).has(i)?'[x]':'[ ]'} ${i+1}. ${s}`).join('\n')}\n\nYOUR OUTPUT\n${selectedChallenge.output}\n\nREFLECT\nWhat surprised you? What would you change? What would you try next?\n\nThis is a self-guided practice brief, not an enrolment, graded assessment, or certificate.\nSpark your curiosity, shape your future.\n`);$('#challenge-status').textContent='Your brief download has started.';});}

const form=$('#enquiry-form');
if(form){const fields=$('#enquiry-fields');fields.disabled=false;const params=new URLSearchParams(location.search);const type=$('#enquiry-type'),program=$('#program-interest');if([...type.options].some(o=>o.value===params.get('type')))type.value=params.get('type');if(programs.some(p=>p.slug===params.get('program')))program.value=params.get('program');function updateType(){const partner=['institution','industry'].includes(type.value);$('#organization-field').hidden=!partner;$('#organization').required=partner;if(['institution','industry','mentor'].includes(type.value)&&program.value==='undecided')program.value='collaboration';}updateType();type.addEventListener('change',updateType);const live=Boolean(contactConfig.endpoint);if(live){$('#submit-enquiry').innerHTML='Send my enquiry <span aria-hidden="true">↗</span>';$('#contact-mode-note').textContent='Send your question to ZelSpark. We’ll confirm here if it is received.';$('#consent-label').textContent='I agree that ZelSpark may use these details to respond to this enquiry as described in its privacy notice.';$('.contact-note h3').textContent='Send an enquiry.';$('.contact-note .tag').textContent='LET’S TALK';}
const message=$('#message');message.addEventListener('input',()=>{$('#message-count').textContent=`${message.value.length} / 2000`;});
function errorFor(name,text){const input=form.elements.namedItem(name);input?.setAttribute('aria-invalid',String(Boolean(text)));const box=$(`#${name}-error`);if(box)box.textContent=text;}
function validate(){const errors=[];const name=form.elements.name.value.trim(),email=form.elements.email.value.trim(),phone=form.elements.phone.value.trim(),org=form.elements.organization.value.trim(),msg=message.value.trim();errorFor('name',name.length<2?'Please enter a name with at least 2 characters.':'');if(name.length<2)errors.push(form.elements.name);const emailBad=!email||!form.elements.email.validity.valid;errorFor('email',emailBad?'Please enter a valid email address.':'');if(emailBad)errors.push(form.elements.email);const phoneBad=Boolean(phone)&&(!/^[+\d\s().-]+$/.test(phone)||phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15);errorFor('phone',phoneBad?'Use 7–15 digits, with an optional country code.':'');if(phoneBad)errors.push(form.elements.phone);const orgBad=form.elements.organization.required&&org.length<2;errorFor('organization',orgBad?'Please enter your institution or organization.':'');if(orgBad)errors.push(form.elements.organization);errorFor('message',msg.length<15?'Please add a little more detail (at least 15 characters).':'');if(msg.length<15)errors.push(message);const consentBad=!$('#consent').checked;errorFor('consent',consentBad?(live?'Please confirm how we may use your details.':'Please confirm that you understand this is a draft.'): '');if(consentBad)errors.push($('#consent'));if(errors.length){$('#form-status').textContent=`Please check ${errors.length===1?'the highlighted field':`the ${errors.length} highlighted fields`}.`;errors[0].focus();return false;}$('#form-status').textContent='';return true;}
$$('input,textarea,select',form).forEach(input=>input.addEventListener('input',()=>{if(input.getAttribute('aria-invalid')==='true')errorFor(input.name,'');}));
let draft=null,draftText='';
form.addEventListener('submit',async e=>{e.preventDefault();if(form.elements.website.value)return;if(!validate())return;draft={name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),phone:form.elements.phone.value.trim(),type:type.value,organization:form.elements.organization.required?form.elements.organization.value.trim():'',program:program.value,message:message.value.trim(),consent:$('#consent').checked};const typeLabel=type.options[type.selectedIndex].textContent;const programLabel=program.options[program.selectedIndex].textContent;const rows=[['Name',draft.name],['Email',draft.email],...(draft.phone?[['Phone',draft.phone]]:[]),['Here as',typeLabel],...(draft.organization?[['Organization',draft.organization]]:[]),['Interest',programLabel],['Message',draft.message]];draftText=`ZELSPARK — ${live?'ENQUIRY COPY':'UNSENT ENQUIRY DRAFT'}\n\n${rows.map(([k,v])=>`${k}: ${v}`).join('\n\n')}\n\n${live?'Keep this copy for your records.':'This draft has NOT been sent to ZelSpark. It was prepared locally in the website preview.'}\n`;const summary=$('#enquiry-summary');summary.replaceChildren();rows.forEach(([key,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);summary.append(row);});
if(live){const submit=$('#submit-enquiry');submit.disabled=true;submit.textContent='Sending…';$('#form-status').textContent='Sending your enquiry…';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),contactConfig.timeoutMs);try{const endpoint=new URL(contactConfig.endpoint,location.origin);if(endpoint.protocol!=='https:')throw new Error('Secure endpoint required');const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify({...draft,source:'zelspark-website'}),signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok||body.ok!==true)throw new Error('Submission not confirmed');$('#result-title').textContent='Your enquiry was received.';$('#result-message').textContent='Thank you for sharing what you’d like to explore.';$('#download-enquiry').textContent='Download a copy ↓';$('#edit-enquiry').hidden=true;}catch(error){$('#form-status').textContent=error.name==='AbortError'?'The request timed out. We can’t confirm whether it arrived. Please wait before trying again.':'We couldn’t confirm your enquiry was received. Your details are still here; please try again later.';return;}finally{clearTimeout(timeout);submit.disabled=false;submit.innerHTML='Send my enquiry <span aria-hidden="true">↗</span>';}}
form.hidden=true;$('#enquiry-result').hidden=false;$('#enquiry-result').focus();});
$('#edit-enquiry').addEventListener('click',()=>{$('#enquiry-result').hidden=true;form.hidden=false;$('#full-name').focus();});$('#download-enquiry').addEventListener('click',()=>downloadText('ZelSpark-enquiry-draft.txt',draftText));}

if(document.querySelector('.journey-site')){
  import('./journey.js').catch(()=>{});
  const panels=[...document.querySelectorAll('[data-journey]')];
  const site=document.querySelector('.journey-site');
  const rail=document.querySelector('#journey-rail-fill');
  const links=[...document.querySelectorAll('.journey-rail-numbers a')];
  let scheduled=false;
  const update=()=>{scheduled=false;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);const progress=Math.min(1,scrollY/max);document.documentElement.style.setProperty('--journey-progress',progress);site.classList.toggle('is-scrolling',scrollY>innerHeight*.4&&scrollY<site.offsetHeight-innerHeight*.6);if(rail)rail.style.height=`${Math.min(100,progress*150)}%`;let active=0;for(let i=0;i<panels.length;i++){if(panels[i].getBoundingClientRect().top<innerHeight*.55)active=i;}links.forEach((a,i)=>a.classList.toggle('is-active',i===active-1));};
  addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update);}},{passive:true});
  addEventListener('resize',update);update();
}
